buildscript {

    repositories {
//        mavenLocal()
        maven { url "https://repo1.maven.org/maven2/" }
    }

    dependencies {
        classpath(
                "io.spring.gradle:dependency-management-plugin:1.1.4"
        )
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

allprojects {
    group 'com.bp'
    version '1.0'
    apply plugin: 'idea'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    sourceCompatibility = 17
    targetCompatibility = 17

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
    tasks.withType(Test) {
        useJUnitPlatform()
    }
    
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://repo.spring.io/milestone' }
        maven { url 'https://repo.spring.io/snapshot' }
    }

    dependencyManagement {
        dependencies {
            dependency group: 'org.springframework', name: 'spring-core', version: '6.2.0-SNAPSHOT' // Using 6.2/7.0 equivalent for now
            dependency group: 'org.springframework', name: 'spring-context', version: '6.2.0-SNAPSHOT'
            dependency group: 'org.springframework', name: 'spring-aspects', version: '6.2.0-SNAPSHOT'
            dependency group: 'org.springframework', name: 'spring-web', version: '6.2.0-SNAPSHOT'
            dependency group: 'org.springframework', name: 'spring-jdbc', version: '6.2.0-SNAPSHOT'
            dependency group: 'org.springframework', name: 'spring-orm', version: '6.2.0-SNAPSHOT'
            dependency group: 'org.springframework', name: 'spring-test', version: '6.2.0-SNAPSHOT'
        }
    }


    dependencies {
        implementation 'org.springframework:spring-core'
        implementation 'org.springframework:spring-context'
        implementation group: 'jakarta.inject', name: 'jakarta.inject-api', version: '2.0.1'
        implementation group: 'jakarta.annotation', name: 'jakarta.annotation-api', version: '3.0.0'
        compileOnly 'org.projectlombok:lombok:1.18.32'
        annotationProcessor 'org.projectlombok:lombok:1.18.32'
        testImplementation 'org.springframework:spring-test'
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    }
}

